v0.0.3-beta

diff --git a/rcmd b/rcmd
--- a/rcmd
+++ b/rcmd
@@ -23,47 +23,29 @@ printf "${STOP}"
 getopts s safe_mode
 cd "$HOME" || exit
 
-# Checking args
-if [ "$#" -lt 4 ] && [ "$safe_mode" = "?" ];then
-    if [ -z "$1" ];then
-        if [ "$LANGUAGE" = pt_BR ];then
-            echo -e "${GREEN_LIGHT}Tempo de espera do comando:"
-            read -r wait_time
-            echo "Unidade de tempo: [s/m/h/d/...]"
-            read -r tm
-            echo -e "nome de Usuário do GitHub:"
-            read -r user_git
-            echo -e "Email do GitHub:"
-            read -r email_git
-            echo -e "Quer usar o modo salvar bateria? [s/n]${STOP}"
-            read -r sf
-            if [ "$sf" = "s" ];then safe_mode=$"s"; fi
-            echo
-        else
-            echo -e "${GREEN}Command wait time: "
-            read -r wait_time
-            echo "time measurement unit: [s/m/h/d/...]"
-            read -r tm
-            echo -e "Github user:"
-            read -r user_git
-            echo -e "GitHub email:"
-            read -r email_git
-            echo -e "Do you want to use safe_mode? [y/n]${STOP}"
-            read -r sf
-            if [ "$sf" = "y" ];then safe_mode=$"s"; fi
-            echo
-        fi
-    else
-        printf "${RED}"
-        if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [ -s ] <tempo_espera> <unidade_tempo> <usuario_git> <email_git>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time> <unit_time> <github_user> <github_email>'; fi
-        exit 1
-    fi
-elif [ "$#" -lt 5 ] && [ "$safe_mode" = "s" ];then
-    if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [ -s ] <tempo_espera> <unidade_tempo> <usuario_git> <email_git>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time> <unit_time> <github_user> <github_email>'; fi
+# MENU
+while true; do
+    clear
+    printf "${GREEN_LIGHT}"
+    figlet -c "Remote Shell"
     printf "${STOP}"
-    exit 1
-fi
+    printf "${CYAN}"
+    if [ "$LANGUAGE" = "pt_BR" ]; then echo -e '\nEscolha uma opção abaixo:\n[1] - Resetar\n[2] - Executar\nSua escolha:'; else echo -e "Choose an option below\n[1] - Reset\n[2] - Execute\nYour choose:"; fi
+    read -r menuOption
+    printf "${STOP}"
+    case "${menuOption}" in
+        1|2)
+            break
+        ;;
+        *)
+            printf "${RED}"
+            if [ "$LANGUAGE" = "pt_BR" ]; then echo "Opção inválida!"; else "Invalid Option!"; fi
+            printf "${STOP}"
+        ;;
+    esac
+done
 
+# Check Connection
 printf "${BLUE}"
 clear
 figlet -c "Remote Shell"
@@ -71,33 +53,96 @@ if [ "$LANGUAGE" = "pt_BR" ]; then echo -e "\nChecando a conexão..."; else echo
 check_connection=$(ping -w 1 githubstatus.com)
 printf "${STOP}"
 
+if [ -z "$check_connection" ];then
+    printf "${RED_LIGHT}"
+    if [ "$LANGUAGE" = "pt_BR" ]; then echo -e "Falha na conexão com a rede\nVerifique isso e tente novamente."; else echo -e "Failed to connect to the network\nCheck this and try again"; fi
+    printf "${STOP}"
+    exit 1
+fi
+
+# Checking args
+if [ "$menuOption" = 2 ]; then
+    if [ "$#" -lt 3 ] && [ "$safe_mode" = "?" ];then
+        if [ -z "$1" ];then
+            if [ "$LANGUAGE" = pt_BR ];then
+                echo -e "${GREEN_LIGHT}Tempo de espera do comando: [1s/1m/1h/1d...]"
+                read -r wait_time
+                if [ -d "$HOME/.cmd" ]; then
+                    echo
+                else
+                    echo -e "nome de Usuário do GitHub:"
+                    read -r user_git
+                    echo -e "Email do GitHub:"
+                    read -r email_git
+                fi
+                echo -e "Quer usar o modo salvar bateria? [s/n]${STOP}"
+                read -r sf
+                if [ "$sf" = "s" ];then safe_mode=$"s"; fi
+                echo
+            else
+                echo -e "${GREEN}Command wait time: [1s/1m/1h/1d...]"
+                read -r wait_time
+                if [ -d "$HOME/.cmd" ]; then
+                    echo
+                else
+                    echo -e "Github user:"
+                    read -r user_git
+                    echo -e "GitHub email:"
+                    read -r email_git
+                fi
+                echo -e "Do you want to use safe_mode? [y/n]${STOP}"
+                read -r sf
+                if [ "$sf" = "y" ];then safe_mode=$"s"; fi
+                echo
+            fi
+        else
+            if [ -z "$1" ];then
+            printf "${RED}"
+                if [ -d "$HOME/.cmd" ]; then
+                    if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [ -s ] <tempo_espera>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time>'; fi
+                else
+                    if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [ -s ] <tempo_espera> <usuario_git> <email_git>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time> <github_user> <github_email>'; fi
+                fi
+                sleep 1
+                exit 1
+            fi
+        fi
+    elif [ "$#" -lt 4 ] && [ "$safe_mode" = "s" ];then
+        if [ -d "$HOME/.cmd" ] && [ "$#" -lt 2 ]; then
+            if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [ -s ] <tempo_espera> <usuario_git> <email_git>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time>'; fi
+        else
+            if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [ -s ] <tempo_espera> <usuario_git> <email_git>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time> <github_user> <github_email>'; fi
+        fi
+        printf "${STOP}"
+        sleep 2
+        exit 1
+    fi
+fi
+
 # Variables
 #check_rootUsers=$UID
 check_git=$(which git)
 check_gh=$(which gh)
 if [ "$1" = "-s" ];then
     wait_time=$2
-    tm=$3
-    user_git=$4
-    email_git=$5
+    if [ -d "$HOME/.cmd" ];then
+        echo
+    else
+        user_git=$3
+        email_git=$4
+    fi
 elif [ -n "$1" ];then
     wait_time=$1
-    tm=$2
-    user_git=$3
-    email_git=$4
+    if [ -d "$HOME/.cmd" ];then
+        echo
+    else
+        user_git=$2
+        email_git=$3
+    fi
 fi
-menuOption=""
-
-
-# Check Connection
-if [ -z "$check_connection" ];then
-    printf "${RED_LIGHT}"
-    if [ "$LANGUAGE" = "pt_BR" ]; then echo -e "Falha na conexão com a rede\nVerifique isso e tente novamente."; else echo -e "Failed to connect to the network\nCheck this and try again"; fi
-    printf "${STOP}"
-    exit 1
 
 # Depends Check
-elif [ -z "$check_git" ] || [ -z "$check_gh" ];then
+if [ -z "$check_git" ] || [ -z "$check_gh" ];then
     printf "${ORANGE}"
     if [ "$LANGUAGE" = "pt_BR" ]; then echo -e "Dependencias não estão instaladas e o programa depende delas.\nDeseja instalar? [s/n]"; else echo -e "Depends are not installed and the program depends on it to work.\nDo you want to install it? [y/n]"; fi
     printf "${STOP}"
@@ -122,28 +167,6 @@ elif [ -z "$check_git" ] || [ -z "$check_gh" ];then
     fi
 fi
 
-# MENU
-while true; do
-    clear
-    printf "${GREEN_LIGHT}"
-    figlet -c "Remote Shell"
-    printf "${STOP}"
-    printf "${CYAN}"
-    if [ "$LANGUAGE" = "pt_BR" ]; then echo -e '\nEscolha uma opção abaixo:\n[1] - Resetar\n[2] - Executar\nSua escolha:'; else echo -e "Choose an option below\n[1] - Reset\n[2] - Execute\nYour choose:"; fi
-    read -r menuOption
-    printf "${STOP}"
-    case "${menuOption}" in
-        1|2)
-            break
-        ;;
-        *)
-            printf "${RED}"
-            if [ "$LANGUAGE" = "pt_BR" ]; then echo "Opção inválida!"; else "Invalid Option!"; fi
-            printf "${STOP}"
-        ;;
-    esac
-done
-
 # Running...
 if [ "$menuOption" -eq 1 ]; then
     printf "${ORANGE_LIGHT}"
@@ -163,12 +186,12 @@ elif [ "$menuOption" -eq 2 ]; then
     figlet -c "Remote Shell"
     printf "${GREEN}"
     if [ "$LANGUAGE" = pt_BR ]; then echo "Configurando repositório remoto..."; else echo "Setting remote repo..."; fi
-    git config --global user.name "$user_git"
-    git config --global user.email "$email_git"
 
     if [ -d ".cmd" ]; then
         echo
     else
+        git config --global user.name "$user_git"
+        git config --global user.email "$email_git"
         mkdir "$HOME/.cmd"
         touch comando "$HOME/.cmd"
         echo "ls ." > "$HOME/.cmd/comando"
@@ -199,12 +222,12 @@ elif [ "$menuOption" -eq 2 ]; then
         if [ "$LANGUAGE" = pt_BR ];then echo "Esperando pelo comando..."; else echo "Waiting for command..."; fi
         case "${safe_mode}" in
             s)
-                sleep "$wait_time""$tm"
+                sleep "$wait_time"
                 nmcli r all on
                 sleep 7s
             ;;
             ?)
-                sleep "$wait_time""$tm"
+                sleep "$wait_time"
             ;;
         esac
         git init &> /dev/null
