v0.0.3-beta

diff --git a/rcmd b/rcmd
--- a/rcmd
+++ b/rcmd
@@ -23,6 +23,60 @@ printf "${STOP}"
 getopts s safe_mode
 cd "$HOME" || exit
 
+# Checking args
+if [ "$#" -lt 3 ] && [ "$safe_mode" = "?" ];then
+    if [ -z "$1" ] || [ ! -d "$HOME/.cmd" ];then
+        if [ "$LANGUAGE" = pt_BR ];then
+            echo -e "${GREEN_LIGHT}Tempo de espera do comando: [1s/1m/1h/1d...]"
+            read -r wait_time
+            if [ ! -d "$HOME/.cmd" ]; then
+                echo -e "nome de Usuário do GitHub:"
+                read -r user_git
+                echo -e "Email do GitHub:"
+                read -r email_git
+            fi
+            echo -e "Quer usar o modo salvar bateria? [s/n]"
+            read -r sf
+        else
+            echo -e "${GREEN}Command wait time: [1s/1m/1h/1d...]"
+            read -r wait_time
+            if [ ! -d "$HOME/.cmd" ]; then
+                echo -e "Github user:"
+                read -r user_git
+                echo -e "GitHub email:"
+                read -r email_git
+            fi
+            echo -e "Do you want to use safe_mode? [y/n]${STOP}"
+            read -r sf
+        fi
+        if [ "$sf" = "y" ] || [ "$sf" = "s" ];then safe_mode=$"s"; fi
+        echo
+    else
+        if [ -z "$1" ];then
+        printf "${RED}"
+            if [ -d "$HOME/.cmd" ]; then
+                if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [ -s ] <tempo_espera>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time>'; fi
+            else
+                if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [ -s ] <tempo_espera> <usuario_git> <email_git>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time> <github_user> <github_email>'; fi
+            fi
+            sleep 1
+            exit 1
+        fi
+    fi
+elif [ "$#" -lt 4 ] && [ "$safe_mode" = "s" ];then
+    printf "${RED}"
+    if [ -d "$HOME/.cmd" ] && [ "$#" -lt 2 ]; then
+        if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Argumento inválido!\nUso: rcmd [ -s ] <tempo_espera> <usuario_git> <email_git>'; else echo -e 'Invalid argument!\nUsage: rcmd [-s] <wait_time>'; fi
+        sleep 1
+        exit 1
+    elif [ "$#" -lt 2 ]; then
+        if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Argumento inválido!\nUso: rcmd [ -s ] <tempo_espera> <usuario_git> <email_git>'; else echo -e 'Invalid argument!\nUsage: rcmd [-s] <wait_time> <github_user> <github_email>'; fi
+        sleep 1
+        exit 1
+    fi
+    printf "${STOP}"
+fi
+
 # MENU
 while true; do
     clear
@@ -41,6 +95,7 @@ while true; do
             printf "${RED}"
             if [ "$LANGUAGE" = "pt_BR" ]; then echo "Opção inválida!"; else "Invalid Option!"; fi
             printf "${STOP}"
+            sleep 1
         ;;
     esac
 done
@@ -60,65 +115,6 @@ if [ -z "$check_connection" ];then
     exit 1
 fi
 
-# Checking args
-if [ "$menuOption" = 2 ]; then
-    if [ "$#" -lt 3 ] && [ "$safe_mode" = "?" ];then
-        if [ -z "$1" ];then
-            if [ "$LANGUAGE" = pt_BR ];then
-                echo -e "${GREEN_LIGHT}Tempo de espera do comando: [1s/1m/1h/1d...]"
-                read -r wait_time
-                if [ -d "$HOME/.cmd" ]; then
-                    echo
-                else
-                    echo -e "nome de Usuário do GitHub:"
-                    read -r user_git
-                    echo -e "Email do GitHub:"
-                    read -r email_git
-                fi
-                echo -e "Quer usar o modo salvar bateria? [s/n]${STOP}"
-                read -r sf
-                if [ "$sf" = "s" ];then safe_mode=$"s"; fi
-                echo
-            else
-                echo -e "${GREEN}Command wait time: [1s/1m/1h/1d...]"
-                read -r wait_time
-                if [ -d "$HOME/.cmd" ]; then
-                    echo
-                else
-                    echo -e "Github user:"
-                    read -r user_git
-                    echo -e "GitHub email:"
-                    read -r email_git
-                fi
-                echo -e "Do you want to use safe_mode? [y/n]${STOP}"
-                read -r sf
-                if [ "$sf" = "y" ];then safe_mode=$"s"; fi
-                echo
-            fi
-        else
-            if [ -z "$1" ];then
-            printf "${RED}"
-                if [ -d "$HOME/.cmd" ]; then
-                    if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [ -s ] <tempo_espera>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time>'; fi
-                else
-                    if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [ -s ] <tempo_espera> <usuario_git> <email_git>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time> <github_user> <github_email>'; fi
-                fi
-                sleep 1
-                exit 1
-            fi
-        fi
-    elif [ "$#" -lt 4 ] && [ "$safe_mode" = "s" ];then
-        if [ -d "$HOME/.cmd" ] && [ "$#" -lt 2 ]; then
-            if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [ -s ] <tempo_espera> <usuario_git> <email_git>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time>'; fi
-        else
-            if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [ -s ] <tempo_espera> <usuario_git> <email_git>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time> <github_user> <github_email>'; fi
-        fi
-        printf "${STOP}"
-        sleep 2
-        exit 1
-    fi
-fi
-
 # Variables
 #check_rootUsers=$UID
 check_git=$(which git)
@@ -127,7 +123,7 @@ if [ "$1" = "-s" ];then
     wait_time=$2
     if [ -d "$HOME/.cmd" ];then
         echo
-    else
+    elif [ -z "$user_git" ] && [ -z "$email_git" ];then
         user_git=$3
         email_git=$4
     fi
@@ -135,7 +131,7 @@ elif [ -n "$1" ];then
     wait_time=$1
     if [ -d "$HOME/.cmd" ];then
         echo
-    else
+    elif [ -z "$user_git" ] && [ -z "$email_git" ];then
         user_git=$2
         email_git=$3
     fi
@@ -176,7 +172,7 @@ if [ "$menuOption" -eq 1 ]; then
     printf "${STOP}"
     printf "${PURPLE}"
     gh repo delete .cmd --confirm
-    if [ -e "$HOME/.cmd" ]; then
+    if [ -d "$HOME/.cmd" ]; then
         rm -rf "$HOME"/.cmd
     fi
     printf "${STOP}"
@@ -187,9 +183,7 @@ elif [ "$menuOption" -eq 2 ]; then
     printf "${GREEN}"
     if [ "$LANGUAGE" = pt_BR ]; then echo "Configurando repositório remoto..."; else echo "Setting remote repo..."; fi
 
-    if [ -d ".cmd" ]; then
-        echo
-    else
+    if [ ! -d ".cmd" ]; then
         git config --global user.name "$user_git"
         git config --global user.email "$email_git"
         mkdir "$HOME/.cmd"
@@ -200,7 +194,7 @@ elif [ "$menuOption" -eq 2 ]; then
         touch README.md "$HOME/.cmd"
         cd "$HOME/.cmd" || exit
         echo "* Put a command inside the comando file to be executed remotely in the remote-shell program." > "$HOME/.cmd/README.md"
-        echo "* You can see the execution log in the rcmd.log file." >> "$HOME/cmd/README.md"
+        echo "* You can see the execution log in the rcmd.log file." >> "$HOME/.cmd/README.md"
 
         git init
         git add .
