new 0.0.1-beta

diff --git a/rcmd b/rcmd
--- a/rcmd
+++ b/rcmd
@@ -1,19 +1,51 @@
 #!/bin/bash
 
+figlet "Remote Shell"
 getopts s safe_mode
-echo "$safe_mode"
 cd "$HOME" || exit
 
 # Checking args
-if [ "$#" -lt 3 ] && [ "$safe_mode" = "?" ];then
-    if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [-s] <tempo_espera> <usuario_git> <email_git>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time> <github_user> <github_email>'; fi
-    exit 1
-elif [ "$#" -lt 4 ] && [ "$safe_mode" = "s" ];then
-    if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [-s] <tempo_espera> <usuario_git> <email_git>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time> <github_user> <github_email>'; fi
+if [ "$#" -lt 4 ] && [ "$safe_mode" = "?" ];then
+    if [ -z "$1" ];then
+        if [ "$LANGUAGE" = pt_BR ];then
+            echo -e "Tempo de espera do comando:"
+            read -r wait_time
+            echo "Unidade de tempo: [s/m/h/d/...]"
+            read -r tm
+            echo -e "nome de Usuário do GitHub:"
+            read -r user_git
+            echo -e "Email do GitHub:"
+            read -r email_git
+            echo -e "Quer usar o modo salvar bateria? [s/n]"
+            read -r sf
+            if [ "$sf" = "s" ];then safe_mode=$"s"; fi
+            echo
+        else
+            echo -e "Command wait time: "
+            read -r wait_time
+            echo "time measurement unit: [s/m/h/d/...]"
+            read -r tm
+            echo -e "Github user:"
+            read -r user_git
+            echo -e "GitHub email:"
+            read -r email_git
+            echo -e "Do you want to use safe_mode? [y/n]"
+            read -r sf
+            if [ "$sf" = "y" ];then safe_mode=$"s"; fi
+            echo
+        fi
+    else
+        if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [ -s ] <tempo_espera> <unidade_tempo> <usuario_git> <email_git>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time> <unit_time> <github_user> <github_email>'; fi
+        exit 1
+    fi
+elif [ "$#" -lt 5 ] && [ "$safe_mode" = "s" ];then
+    if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Comando inválido!\nUso: rcmd [ -s ] <tempo_espera> <unidade_tempo> <usuario_git> <email_git>'; else echo -e 'Invalid command!\nUsage: rcmd [-s] <wait_time> <unit_time> <github_user> <github_email>'; fi
     exit 1
 fi
 
-if [ "$LANGUAGE" = "pt_BR" ]; then echo "Checando a conexão..."; else echo "Checking connection..."; fi
+clear
+figlet "Remote Shell"
+if [ "$LANGUAGE" = "pt_BR" ]; then echo -e "\nChecando a conexão..."; else echo -e "\nChecking connection..."; fi
 check_connection=$(ping -w 1 githubstatus.com)
 
 # Variables
@@ -22,13 +54,14 @@ check_git=$(which git)
 check_gh=$(which gh)
 if [ "$1" = "-s" ];then
     wait_time=$2
+    tm=$3
+    user_git=$4
+    email_git=$5
+elif [ -n "$1" ];then
+    wait_time=$1
+    tm=$2
     user_git=$3
     email_git=$4
-else
-    wait_time=$1
-    user_git=$2
-    email_git=$3
-
 fi
 menuOption=""
 
@@ -56,12 +89,16 @@ elif [ -z "$check_git" ] || [ -z "$check_gh" ];then
         if [ "$LANGUAGE" = "pt_BR" ]; then echo "Opção inválida!"; else "Invalid Option!"; fi
         if [ "$LANGUAGE" = "pt_BR" ]; then echo "Saindo..."; else echo "Exitting..."; fi
         sleep 1
+        exit
     fi
 fi
 
 # MENU
+
 while true; do
-    if [ "$LANGUAGE" = "pt_BR" ]; then echo -e 'Escolha uma opção abaixo:\n[1] - Resetar\n[2] - Executar\nSua escolha:'; else echo -e "Choose an option below\n[1] - Reset\n[2] - Execute\nYour choose:"; fi
+    clear
+    figlet "Remote Shell"
+    if [ "$LANGUAGE" = "pt_BR" ]; then echo -e '\nEscolha uma opção abaixo:\n[1] - Resetar\n[2] - Executar\nSua escolha:'; else echo -e "Choose an option below\n[1] - Reset\n[2] - Execute\nYour choose:"; fi
     read -r menuOption
     case "${menuOption}" in
         1|2)
@@ -84,38 +121,40 @@ elif [ "$menuOption" -eq 2 ]; then
     git config --global user.email "$email_git"
 
     if [ -d "cmd" ]; then
-        echo "Running..."
-        else
-            mkdir "$HOME/cmd"
-            touch comando "$HOME/cmd"
-            echo "ls ." > "$HOME/cmd/comando"
-            touch rcmd.log "$HOME/cmd"
-            echo " " > "$HOME/cmd/rcmd.log"
-            touch README.md "$HOME/cmd"
-            cd "$HOME/cmd" || exit
-            echo "* Put a command inside the comando file to be executed remotely in the remote-shell program." > "$HOME/cmd/README.md"
-            echo "* You can see the execution log in the rcmd.log file." >> "$HOME/cmd/README.md"
-            
-            git init
-            git add .
-            git add comando rcmd.log README.md
-            git commit -m "First commit"
-            gh repo create -s . --private
-            git remote add origin "https://github.com/$2/cmd.git"
-            git push -u origin master
+        echo
+    else
+         mkdir "$HOME/cmd"
+         touch comando "$HOME/cmd"
+         echo "ls ." > "$HOME/cmd/comando"
+         touch rcmd.log "$HOME/cmd"
+         echo " " > "$HOME/cmd/rcmd.log"
+         touch README.md "$HOME/cmd"
+         cd "$HOME/cmd" || exit
+         echo "* Put a command inside the comando file to be executed remotely in the remote-shell program." > "$HOME/cmd/README.md"
+         echo "* You can see the execution log in the rcmd.log file." >> "$HOME/cmd/README.md"
+
+         git init
+         git add .
+         git add comando rcmd.log README.md
+         git commit -m "First commit"
+         gh repo create -s . --private
+         git remote add origin "https://github.com/$2/cmd.git"
+         git push -u origin master 
     fi
 
     cd "$HOME/cmd" || exit
     while true;do
+       clear
+       figlet "Remote Shell"
+       if [ "$LANGUAGE" = pt_BR ];then echo "Esperando pelo comando..."; else echo "Waiting for command..."; fi
         case "${safe_mode}" in
             s)
-                sleep "$(("$wait_time" - 8))"
-                echo "$(("$wait_time" - 8))"
+                sleep "$wait_time"$tm
                 nmcli r all on
-                sleep 8
+                sleep 5s
             ;;
             ?)
-                sleep "$wait_time"
+                sleep "$wait_time"$tm
             ;;
         esac
         git init > /dev/null
@@ -132,7 +171,7 @@ elif [ "$menuOption" -eq 2 ]; then
 
         echo -e "\n* $date" >> ./rcmd.log
         $cmd >> ./rcmd.log 
-        
+
         git add rcmd.log > /dev/null
         git commit -m "commit" > /dev/null
         git push -u origin master > /dev/null
@@ -144,3 +183,4 @@ fi
 if [ "$LANGUAGE" = "pt_BR" ]; then echo "Saindo..."; else echo "Exitting..."; fi
 sleep 1
 exit 0
+
